#!/usr/bin/env bash
# Bash script to install nginx and print out the string "Hello World!".

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo 'Hello World!' > /var/www/html/index.html
sudo service nginx start
