#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes:
# display hours from 0 to 12
# display minutes from 1 to 59

current_hour=0

while [ $current_hour -le 12 ]; do
    echo "Current Hour: $current_hour"

    current_minute=1
    while [ $current_minute -le 59 ]; do
        echo "Current Minute: $current_minute"
        ((current_minute++))
    done

    ((current_hour++))
done
